apps/django_pythonnative/django_pythonnative/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("docs/", include("docs.urls")),
    path("", include("home.urls")),
]

apps/django_pythonnative/docs/urls.py
from django.urls import path

from . import views

app_name = "docs"
urlpatterns = [
    path("", views.index, name="index"),
    path("install", views.install, name="install"),
    path("introduction", views.introduction, name="introduction"),
    path("native-apis", views.native_apis, name="native-apis"),
    path("tutorial", views.tutorial, name="tutorial"),
    path("views", views.views, name="views"),
]

apps/django_pythonnative/home/urls.py
from django.urls import path

from . import views

app_name = "home"
urlpatterns = [
    path("", views.index, name="index"),
]

apps/django_pythonnative/docs/models.py
from django.db import models

# Create your models here.

apps/django_pythonnative/home/models.py
from django.db import models

# Create your models here.

apps/django_pythonnative/docs/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render


def index(request: HttpRequest) -> HttpResponse:
    return render(request, "docs/index.html")


def install(request: HttpRequest) -> HttpResponse:
    return render(request, "docs/install.html")


def introduction(request: HttpRequest) -> HttpResponse:
    return render(request, "docs/introduction.html")


def native_apis(request: HttpRequest) -> HttpResponse:
    return render(request, "docs/native_apis.html")


def tutorial(request: HttpRequest) -> HttpResponse:
    return render(request, "docs/tutorial.html")


def views(request: HttpRequest) -> HttpResponse:
    return render(request, "docs/views.html")

apps/django_pythonnative/home/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render


def index(request: HttpRequest) -> HttpResponse:
    return render(request, "home/index.html")

apps/django_pythonnative/docs/templates/docs/index.html
{% extends "base_generic.html" %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static 'docs/style.css' %}">
{% endblock %}
{% block content %}
  <ul>
    <li><a href="{% url 'docs:introduction' %}">Introduction</a></li>
    <li><a href="{% url 'docs:install' %}">How to install PythonNative</a></li>
    <li><a href="{% url 'docs:tutorial' %}">Tutorial</a></li>
    <li><a href="{% url 'docs:views' %}">Views</a></li>
    <li><a href="{% url 'docs:native-apis' %}">Native APIs</a></li>
  </ul>
{% endblock %}

apps/django_pythonnative/docs/templates/docs/install.html
{% extends "base_generic.html" %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/default.min.css">
  <link rel="stylesheet" href="{% static 'docs/style.css' %}">
{% endblock %}
{% block content %}
  <div class="px-3 py-3">
    <h1>Quick install guide</h1>
    <div class="pb-3">
      <h2>Linux with Android</h2>
      <div class="card">
        <div class="card-body">
          Coming soon.
        </div>
      </div>
    </div>
    <div class="pb-3">
      <h2>macOS with Android</h2>
      <div class="card">
        <div class="card-body">
          <pre><code class="language-bash">pip install pythonnative</code></pre>
          <pre><code class="language-bash">pn doctor android</code></pre>
        </div>
      </div>
    </div>
    <div class="pb-3">
      <h2>macOS with iOS</h2>
      <div class="card">
        <div class="card-body">
          <pre><code class="language-bash">pip install pythonnative</code></pre>
          <pre><code class="language-bash">pn doctor ios</code></pre>
        </div>
      </div>
    </div>
    <div class="pb-3">
      <h2>Windows with Android</h2>
      <div class="card">
        <div class="card-body">
          Coming soon.
        </div>
      </div>
    </div>
  </div>
{% endblock %}
{% block js %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/highlight.min.js"></script>
  <script>hljs.highlightAll();</script>
{% endblock %}

apps/django_pythonnative/docs/templates/docs/introduction.html
{% extends "base_generic.html" %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/default.min.css">
  <link rel="stylesheet" href="{% static 'docs/style.css' %}">
{% endblock %}
{% block content %}
  <div class="px-3 py-3">
    <div class="pb-3">
      <h1>PythonNative at a glance</h1>
      <div class="card">
        <div class="card-body">
          PythonNative is a cross-platform Python tool kit for Android and iOS. It
          allows you to create native UI elements such as buttons and labels in a
          Pythonic way, regardless of whether you're running on iOS or Android.
        </div>
      </div>
    </div>
    <div class="pb-3">
      <h2>Create your app</h2>
      <div class="card">
        <div class="card-body">
          <pre><code class="language-bash">pip install pythonnative</code></pre>
          <pre><code class="language-bash">pn init my_app</code></pre>
          <pre><code class="language-plaintext">.
├── README.md
├── app
│   ├── __init__.py
│   ├── main_page.py
│   └── resources
├── pythonnative.json
├── requirements.txt
└── tests</code></pre>
        </div>
      </div>
    </div>
    <div class="pb-3">
      <h2>Write your views</h2>
      <div class="card">
        <div class="card-body">
          <p>Everything in PythonNative is a view.</p>
          <pre><code class="language-python">import pythonnative as pn


class MainPage(pn.Page):
    def __init__(self, native_instance):
        super().__init__(native_instance)

    def on_create(self):
        super().on_create()
        stack_view = pn.StackView(self.native_instance)
        list_data = ["item_{}".format(i) for i in range(100)]
        list_view = pn.ListView(self.native_instance, list_data)
        stack_view.add_view(list_view)
        self.set_root_view(stack_view)</code></pre>
        </div>
      </div>
    </div>
  </div>
{% endblock %}
{% block js %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/highlight.min.js"></script>
  <script>hljs.highlightAll();</script>
{% endblock %}

apps/django_pythonnative/docs/templates/docs/native_apis.html
{% extends "base_generic.html" %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static 'docs/style.css' %}">
{% endblock %}
{% block content %}
  <div class="px-3 py-3">
    <div class="pb-3">
      <h1>Native APIs</h1>
      <div class="card">
        <div class="card-body">
          <p>These are the native APIs that PythonNative can access.</p>
          <div class="table-responsive">
            <table class="table table-bordered table-striped">
              <thead>
              <tr>
                <th>PythonNative Class</th>
                <th>Android Class</th>
                <th>iOS Class</th>
                <th>Implemented</th>
              </tr>
              </thead>
              <tbody>
              <tr>
                <td>Accelerometer</td>
                <td><a href="https://developer.android.com/reference/android/hardware/SensorManager">android.hardware.SensorManager</a></td>
                <td><a href="https://developer.apple.com/documentation/coremotion/cmmotionmanager">CMMotionManager</a></td>
                <td>No</td>
              </tr>
              <tr>
                <td>BatteryInfo</td>
                <td><a href="https://developer.android.com/reference/android/os/BatteryManager">android.os.BatteryManager</a></td>
                <td><a href="https://developer.apple.com/documentation/uikit/uidevice/1620052-batterylevel">UIDevice</a></td>
                <td>No</td>
              </tr>
              <tr>
                <td>Camera</td>
                <td><a href="https://developer.android.com/reference/android/hardware/Camera">android.hardware.Camera</a></td>
                <td><a href="https://developer.apple.com/documentation/avfoundation/avcapturedevice">AVCaptureDevice</a></td>
                <td>No</td>
              </tr>
              <tr>
                <td>Clipboard</td>
                <td><a href="https://developer.android.com/reference/android/content/ClipboardManager">android.content.ClipboardManager</a></td>
                <td><a href="https://developer.apple.com/documentation/uikit/uipasteboard">UIPasteboard</a></td>
                <td>No</td>
              </tr>
              <tr>
                <td>DeviceInfo</td>
                <td><a href="https://developer.android.com/reference/android/os/Build">android.os.Build</a></td>
                <td><a href="https://developer.apple.com/documentation/uikit/uidevice">UIDevice</a></td>
                <td>No</td>
              </tr>
              <tr>
                <td>Filesystem</td>
                <td><a href="https://developer.android.com/reference/java/nio/file/Files">java.nio.file.Files</a></td>
                <td><a href="https://developer.apple.com/documentation/foundation/nsfilemanager">NSFileManager</a></td>
                <td>No</td>
              </tr>
              <tr>
                <td>Geolocation</td>
                <td><a href="https://developer.android.com/reference/android/location/LocationManager">android.location.LocationManager</a></td>
                <td><a href="https://developer.apple.com/documentation/corelocation/cllocationmanager">CLLocationManager</a></td>
                <td>No</td>
              </tr>
              <tr>
                <td>NetworkInfo</td>
                <td><a href="https://developer.android.com/reference/android/net/ConnectivityManager">android.net.ConnectivityManager</a></td>
                <td><a href="https://developer.apple.com/library/archive/samplecode/Reachability/Introduction/Intro.html">Reachability</a></td>
                <td>No</td>
              </tr>
              <tr>
                <td>Notifications</td>
                <td><a href="https://developer.android.com/reference/android/app/NotificationManager">android.app.NotificationManager</a></td>
                <td><a href="https://developer.apple.com/documentation/usernotifications/unusernotificationcenter">UNUserNotificationCenter</a></td>
                <td>No</td>
              </tr>
              <tr>
                <td>Vibration</td>
                <td><a href="https://developer.android.com/reference/android/os/Vibrator">android.os.Vibrator</a></td>
                <td><a href="https://developer.apple.com/documentation/audiotoolbox/1405248-systemsoundid">AudioServicesPlaySystemSound</a></td>
                <td>No</td>
              </tr>
              <!-- Add more rows as necessary for additional APIs -->
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

apps/django_pythonnative/docs/templates/docs/tutorial.html
{% extends "base_generic.html" %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static 'docs/style.css' %}">
{% endblock %}
{% block content %}
  <div class="px-3 py-3">
    <p>Coming soon.</p>
  </div>
{% endblock %}

apps/django_pythonnative/home/templates/home/index.html
{% extends "base_generic.html" %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static 'home/style.css' %}">
{% endblock %}
{% block content %}
  <img src="{% static 'app_icon.png' %}" alt="PythonNative Icon" class="responsive-image">
{% endblock %}

apps/django_pythonnative/templates/base_generic.html
<!DOCTYPE html>
{% load static %}
<html lang="en" data-bs-theme="light">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>PythonNative</title>
  <!-- Add CSS -->
  <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
      crossorigin="anonymous">
  {% block css %}{% endblock %}
</head>
<body>
<header>
  <!-- https://getbootstrap.com/docs/5.3/components/navbar/#nav -->
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home:index' %}">PythonNative</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
              data-bs-target="#navbarNavAltMarkup"
              aria-controls="navbarNavAltMarkup" aria-expanded="false"
              aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link active" aria-current="page"
             href="{% url 'home:index' %}">Home</a>
          <a class="nav-link active" aria-current="page"
             href="{% url 'docs:index' %}">Docs</a>
        </div>
      </div>
    </div>
  </nav>
</header>

{% block content %}
{% endblock %}

<footer>
  <div class="container">
    <div class="row">
      <div class="col-sm">
        <h5>Social</h5>
        <ul class="list-unstyled">
          <li><a href="https://twitter.com/PythonNative">Twitter</a></li>
          <li><a href="https://www.threads.net/@pythonnative">Threads</a></li>
        </ul>
      </div>
      <div class="col-sm">
        <h5>Learn more</h5>
        <ul class="list-unstyled">
          <li><a href="https://github.com/pythonnative">GitHub</a></li>
          <li><a href="https://pypi.org/project/pythonnative/">PyPI</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

<!-- Add JS -->
<script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
    crossorigin="anonymous"></script>
<script>
  function updateColorMode() {
    if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
      document.documentElement.setAttribute('data-bs-theme', 'dark');
    } else {
      document.documentElement.setAttribute('data-bs-theme', 'light');
    }
  }
  updateColorMode();
  window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', updateColorMode);
</script>
{% block js %}{% endblock %}
</body>
</html>